### ISSUE TITLE
dgl installation error not solved by manually reinstalling compatible torch version

### ISSUE THREAD

**Issue by ncyx** [graeter-group/grappa#20]
**Problem**:  `ImportError: Cannot load Graphbolt C++ library`

Reinstalling dgl-compatible torch version manually (`pip uninstall torch` ; `pip install torch==2.1.0`) did not resolve issue. 

**Solution**: Clean installation of torch==2.1.0 & downgrading cuda to cu118 manually with 

`conda install pytorch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 pytorch-cuda=11.8 -c pytorch -c nvidia`

`conda install -c dglteam/label/th21_cu118 dgl`

With this sequence of steps the `python tests/test_installation.py` passess the test on CUDA.

**Comment by LeifSeute** [comment]
Thank you very much! We included this information in f38d951.
